all:
  hosts:
  children:
    testpi:
      hosts:
        raspi4:
          ansible_host: 192.168.1.146
    unipi:
      hosts:
        alarm.lan:
        tesla.lan:
        edison.lan:
        192.168.1.203:
